name: Destroy Azure Web App
on:
  repository_dispatch:
    types: delete_web_app
jobs:
  create-web-app-infra:      
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_NAME: "${{ github.event.client_payload.repo }}"
      AZURE_SUBSCRIPTION: "${{ github.event.client_payload.subscription }}"
      AZURE_RESOURCE_GROUP: "${{ github.event.client_payload.resource_group }}"
      AZURE_DEPLOY_ENVIRONMENT: "${{ github.event.client_payload.environment }}"
      AZURE_WEB_APP_TYPE: "${{ github.event.client_payload.app_type }}"
      AZURE_WEB_APP_NAME_PREFIX: 'alm-app'
    steps:
    - name: Set env
      run: |
        echo "AZURE_WEB_APP_NAME=${AZURE_WEB_APP_NAME_PREFIX}-${AZURE_WEB_APP_TYPE}-${GITHUB_REPO_NAME}-${AZURE_DEPLOY_ENVIRONMENT}" >> $GITHUB_ENV
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Azure Web App
      run: |
        az webapp delete --name $AZURE_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP

    - name: Update Azure Web App Endpoints File
      run: |
        jq 'del(.[($AZURE_WEB_APP_NAME)])' < .github/webapps/webapps.json > tmp_webapps.json && mv tmp_webapps.json .github/webapps/webapps.json
        git config --global user.email "siva.medapati@blueyonder.com"
        git config --global user.name "Siva Medapati"
        git config pull.rebase false
        git pull origin ${BRANCH}
        git add -f .github/webapps/webapps.json
        git commit -m "added webapp endpoint"
        git push origin ${BRANCH}